### PR TITLE
Init vhi

### PR DESCRIPTION
**Pull request by zackarno**
Main calculations of concern are in the `_targets.R` pipeline in the new [cropland_lte_vhi_thresh](https://github.com/OCHA-DAP/ds-aa-lac-dry-corridor/blob/init-VHI/R/tar_vhi_cropland.R) 

Once targets was run I created an exploratory notebook ([VHI_thresholds.Rmd](https://github.com/OCHA-DAP/ds-aa-lac-dry-corridor/blob/init-VHI/exploration/VHI_thresholds.Rmd)) to checkout the results.

If you will run the `_targets.R` pipeline I recommend doing it as a background process - it might take 45 min or an hour:

you can just navigate to the repo in the terminal and run 

```
caffeinate -i -s Rscript -e 'targets::tar_make()'
```

### CODE REVIEW

**Review by caldwellst — COMMENTED** [review]
So, I'm waiting for the targets script to run, so putting through a few questions while that happens.

1. Am I doing something wrong in `{targets}` where I have to re-run the entire pipeline to then use `tar_load()`? Is there a way someone who hasn't run `tar_make()` can use the stuff? It seems to be quite a big disadvantage since we have a shared drive with the purpose of us being able to re-use data that others have processed, but I imagine I might be doing something wrong.

2. Could the processing be more streamlined by just extracting all raster cells to the countries they are in tabular format? Then it is going to be on the scale of seconds to calculate all the % of cells above and below thresholds. You just need two columns for VHI and cropland alongside a country column.

**Comment by zackarno** [comment]
**on point 1:**

Yes you have to run `tar_make()` to create the object to be able to use `tar_load()` - I guess this is a disadvantage for our setup however we can set the `_target` destination folder to a shared location - just not sure how we want to do this with out set up. Theres good documentation regarding storing targets in AWS bins/Azure - could be awesome.  I guess if we continued w/ gdrive we would want to develop a more project/repo based schema in addition to the `AA_DATA_DIR` - I could see this having some side benefits as well.

Definitely a convenience of shared targets, but on the flip side,  requiring targets to run does ensure the analysis is completely reproducible and works on others computers yielding the same results - but i'm with you especially for very heavy processes.

**in point 2:**
wow, great idea!  I guess we would loose the ability to do weighted fraction zonal stats, but in this case I don't think it would make much of a difference since the cells are so high-resolution.

If you get the `_targets.R` to run successfully and you think the code is correct and produces the correct results. I think the easiest way forward would just be to validate and merge this branch and then create a new one where I test your more efficient idea

**Comment by caldwellst** [comment]
Looks good to me. `_targets` runs well, but took 3 hours ha. I think on the analysis, nothing to change really, but I guess there was nothing to validate against? I would also change the dot plots to be area or line plots, because then you can more easily see the temporal trend, as is, dots just look disconnected.

**Comment by caldwellst** [comment]
On point 2, I think you can do it just in this PR, that's fine, since it's for VHI. Any changes you make are then flagged for review since I've indicated I've read the rest, and all we need to do is just change the target script. I think you can still do weighted fraction stats if you mean weighting by the percent of land? Because you can just extract the percents for weighting as a vector as well (after it's been resampled). But maybe I'm misunderstanding.

**Comment by zackarno** [comment]
> On point 2, I think you can do it just in this PR, that's fine, since it's for VHI. Any changes you make are then flagged for review since I've indicated I've read the rest, and all we need to do is just change the target script. I think you can still do weighted fraction stats if you mean weighting by the percent of land? Because you can just extract the percents for weighting as a vector as well (after it's been resampled). But maybe I'm misunderstanding.

What I meant is the weighted zonal stats per admin boundary. I think it's tricky because you can extract all raster cell values per admin - you will have a data.frame w/ cols `country`, `cell_id`, `value`... but  won't have a frac % per cell_id. Sure there is a way to get that, but then we are basically reinventing zonal stats and **actually** the more that I think about it, I think this process will take just as long if not longer to run the extraction to to tabular format for every step in the time-series. Sure the thresholding would be faster on a data.frame, but it's then a question of what takes longer: extracting raster values or reclassifying raster values -- inkling that the whole process will be somewhat similar. 

ok since the writing the above I was playing with it a bit - you might be right  that there could be some efficiency gains (honestly not sure), but fairly certain it is not worth the effort to re-write as it will be more  complicated (at least than it first sounded to me).

**Comment by zackarno** [comment]
> Looks good to me. `_targets` runs well, but took 3 hours ha. I think on the analysis, nothing to change really, but I guess there was nothing to validate against? I would also change the dot plots to be area or line plots, because then you can more easily see the temporal trend, as is, dots just look disconnected.

yeah good point - i added the lines, agree it looks better

**Comment by zackarno** [comment]
> but I guess there was nothing to validate against?
 
may look into some additional validation down the line, but it's out of scope on this PR -- im trying to hack away at this in small chunks/PRs

**Review by caldwellst — APPROVED** [review]

**Pull request merged**
